version: '3.9'

services:

  fluent-bit:
    image: fluent/fluent-bit:latest
    container_name: fluent-bit
    restart: unless-stopped
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    depends_on:
      - splunk
    networks:
      - anantx-network

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - anantx-network

  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - anantx-network
      - anant-monitoring

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend
    networks:
      - anantx-network
      - anant-monitoring

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    networks:
      - anantx-network

  falco:
    image: falcosecurity/falco:latest
    restart: unless-stopped
    privileged: true
    pid: host
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - /proc:/host/proc:ro
      - /boot:/host/boot:ro
      - /lib/modules:/host/lib/modules:ro
      - /usr:/host/usr:ro
    networks:
      - anantx-network

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: kavachuser
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: anantx
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kavachuser -d anantx"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - anantx-network

  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    restart: unless-stopped
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_GENERAL_TERMS: --accept-sgt-current-at-splunk-com
      SPLUNK_PASSWORD: AnantX@123
    ports:
      - "8001:8000"
      - "8088:8088"
      - "8089:8089"
    volumes:
      - splunk_etc:/opt/splunk/etc
      - splunk_var:/opt/splunk/var
    networks:
      - anantx-network

volumes:
  postgres_data:
  splunk_etc:
  splunk_var:

networks:
  anantx-network:

  anant-monitoring:
    external: true
    name: anant-monitoring
