export const backButtonStyle = {
    padding: "12px 20px",
    borderRadius: "12px",
    border: "none",
    cursor: "pointer",
    marginBottom: "20px",
    background: "#0b69ff",
    color: "#ffffff",
    fontWeight: 700,
    fontSize: "16px",
    lineHeight: "20px",
    fontFamily: "Inter, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial",
    boxShadow: "0 6px 18px rgba(11,105,255,0.12)",
    letterSpacing: "0.2px",
    display: "inline-flex",
    alignItems: "center",
    gap: "8px",
    transition: "transform 0.08s ease, box-shadow 0.12s ease",
    outline: "none",
};
