[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info

[INPUT]
    Name         tail
    Path         /var/lib/docker/containers/*/*.log
    Tag          docker.*

[OUTPUT]
    Name              splunk
    Match             *
    Host              splunk
    Port              8088
    TLS               On
    TLS.Verify        Off
    Splunk_Token      498ff31b-345f-4772-8acf-bd1696256db1
