[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info

[INPUT]
    Name         tail
    Path         /var/lib/docker/containers/*/*.log
    Tag          docker.*

[OUTPUT]
    Name              splunk
    Match             *
    Host              splunk
    Port              8088
    TLS               On
    TLS.Verify        Off
    Splunk_Token      0d8149a7-3fac-407b-a9bb-3f932aa58083
